#!/bin/bash +x

echo Installing NPM packages ...
npm i
echo Generating Typescript types ...
./node_modules/.bin/webidl2ts -d -e -n PhysX -i ../PhysX/physx/source/webidlbindings/src/wasm/PhysXWasm.idl -o input.d.ts
echo Fixing Typescript types ...
node generate.js
