name: PhysX-JS-WebIDL - Build Library

on:
  push

jobs:
  build:
    name: Build PhysX-JS-WebIDL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: recursive

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      
      - name: Build Docker Environment
        run: sudo docker compose up
        
      - name: Build PhysX-JS-WebIDL
        run: sudo docker compose run --rm builder ./make.sh

      # Upload the build results - Retained for 90 days by default
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: Build Products
          path: dist
